### ISSUE TITLE
非对称解密异常

### ISSUE THREAD

**Issue by caihuamao520** [anyboo/UKEY#16]
非对称解密历史加密的数据会出现异常。

**Comment by anyboo** [comment]
场景1:
步骤：
1.加密数据成功后，关闭应用程序。
2.打开应用程序，利用复制的设备识别符（uid）、密文（enc） 进行解密。
解密失败，并有下列提示
![image](https://user-images.githubusercontent.com/2034799/59551133-85e1f800-8fa7-11e9-8d19-92580708a1d1.png)

**Comment by anyboo** [comment]
@caihuamao520 蔡总，验证后关闭呀

**Comment by caihuamao520** [comment]
已解决
